

spring:
  servlet:
    multipart:
      enabled: true
      #允许上传的单个文件大小
      max-file-size: 1GB
      #每次上传请求允许的文件总大小
      max-request-size: 6GB
  mail:
    username: 1605337475@qq.com
    password: dfonedysuodlhigc
    host: smtp.qq.com
    mail:
      properties:
        mail:
          smtl:
            ssl:
              enable: true


  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  type-aliases-package: com.tony.blog.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath:mappers/*Mapper.xml